# Dockerfile para Nginx-RTMP com GStreamer
FROM tiangolo/nginx-rtmp:latest

# Instalar dependências e GStreamer
RUN apt-get update && apt-get install -y \
    gstreamer1.0-tools \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav \
    gstreamer1.0-rtsp \
    curl \
    bc \
    && rm -rf /var/lib/apt/lists/*

# Copiar configurações
COPY nginx.gstreamer.conf /etc/nginx/nginx.conf
COPY cleanup-hls.sh /usr/local/bin/

# Copiar script GStreamer modificado para nginx
COPY ../transcoding/gstreamer/transcode.sh /usr/local/bin/transcode-gstreamer.sh

# Fazer scripts executáveis
RUN chmod +x /usr/local/bin/cleanup-hls.sh
RUN chmod +x /usr/local/bin/transcode-gstreamer.sh

# Criar diretórios necessários
RUN mkdir -p /tmp/hls /var/log/nginx

# Configurar cron para limpeza automática
RUN echo "0 */3 * * * root /usr/local/bin/cleanup-hls.sh >> /var/log/cleanup-hls.log 2>&1" > /etc/crontab

# Expor portas
EXPOSE 1935 8081

# Script de inicialização
RUN echo '#!/bin/bash\n\
# Iniciar cron para limpeza automática\n\
cron\n\
\n\
# Iniciar nginx\n\
exec nginx -g "daemon off;"\n\
' > /start.sh && chmod +x /start.sh

CMD ["/start.sh"]