listen              ${RTMP_PORT};
max_connections      1000;
srs_log_tank         file;
srs_log_level        trace;
srs_log_file         ./objs/srs.log;
daemon               off;

http_api {
    enabled         on;
    listen          1985;
    crossdomain     on;
}

http_server {
    enabled         on;
    listen          ${HLS_HTTP_PORT};
    dir             ${HLS_ROOT_PATH};
}

vhost __defaultVhost__ {
    http_hooks {
        enabled         on;
        on_publish      http://${BACKEND_HOST}:${BACKEND_PORT}/api/streams/callback/publish?name=[stream];
        on_unpublish    http://${BACKEND_HOST}:${BACKEND_PORT}/api/streams/callback/publish_done?name=[stream];
    }

    hls {
        enabled         off;
    }

    exec {
        enabled         on;
        publish         /usr/local/bin/transcode.sh [stream];
    }
}